# Generated by Django 4.2.27 on 2026-04-15 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('zone', models.CharField(blank=True, default='', max_length=40)),
                ('rack', models.CharField(blank=True, default='', max_length=40)),
                ('bin', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='allocation_status',
            field=models.CharField(choices=[('not_allocated', 'Not Allocated'), ('partially_allocated', 'Partially Allocated'), ('fully_allocated', 'Fully Allocated')], default='not_allocated', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='StockBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bins', to='core.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_bins', to='core.sku')),
            ],
            options={
                'unique_together': {('sku', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.PositiveIntegerField()),
                ('picked_qty', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('exception', 'Exception')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='core.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='core.orderitem')),
                ('stock_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='core.stockbin')),
            ],
        ),
    ]
