# Generated by Django 4.2.27 on 2026-04-15 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def backfill_levels(apps, schema_editor):
    Rack = apps.get_model("core", "Rack")
    Level = apps.get_model("core", "Level")
    Bin = apps.get_model("core", "Bin")
    for rack in Rack.objects.all():
        total = max(1, rack.total_levels or rack.levels or 1)
        for i in range(1, total + 1):
            Level.objects.get_or_create(rack_id=rack.id, level_number=i)
    for bin_obj in Bin.objects.filter(level__isnull=True):
        level, _ = Level.objects.get_or_create(rack_id=bin_obj.rack_id, level_number=bin_obj.level_number or 1)
        bin_obj.level_id = level.id
        bin_obj.save(update_fields=["level"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_warehouse_packing_is_box_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inboundputawaytask',
            name='suggested_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_putaway_tasks', to='core.bin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('damaged', 'Damaged')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='rack',
            name='total_levels',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sku',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='core.bin'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='core.bin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='core.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_rows', to='core.rack')),
            ],
            options={
                'ordering': ['level_number'],
                'unique_together': {('rack', 'level_number')},
            },
        ),
        migrations.AddField(
            model_name='bin',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='core.level'),
        ),
        migrations.RunPython(backfill_levels, migrations.RunPython.noop),
    ]
