# Generated by Django 4.2.27 on 2026-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bin_max_capacity_inboundputawaytask_suggested_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_batch',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
