# Generated by Django 4.2.27 on 2026-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_purchaseorderitem_received_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='zone',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
