from django.urls import path

from . import api_views, inbound_views, shipping_views, views


urlpatterns = [
    path("", views.login_view, name="login"),
    path("otp/", views.otp_view, name="otp"),
    path("resend-otp/", views.resend_otp, name="resend_otp"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("api/dashboard/", views.dashboard_api, name="dashboard_api"),
    path("orders/", views.orders_list, name="orders_list"),
    path("orders/create/", views.order_create, name="order_create"),
    path("orders/<int:order_id>/", views.order_detail, name="order_detail"),
    path("orders/<int:order_id>/edit/", views.order_update, name="order_update"),
    path("orders/<int:order_id>/allocate/", views.allocate_order, name="allocate_order"),
    path("orders/<int:order_id>/auto-allocate/", views.allocate_order, name="auto_allocate"),
    path("orders/<int:order_id>/hold/", views.hold_order, name="hold_order"),
    path("allocation/", views.allocation_page, name="allocation"),
    path("picking/", views.pick_task_list, name="pick_task_list"),
    path("picking/tasks/", views.pick_task_monitor, name="pick_task_monitor"),
    path("picking/task/<int:task_id>/", views.pick_task_detail, name="pick_task_detail"),
    path("consolidation/", views.consolidation_queue, name="consolidation_queue"),
    path("consolidation/<int:order_id>/", views.consolidation_detail, name="consolidation_detail"),
    path("consolidation/<int:order_id>/send-packing/", views.consolidation_send_packing, name="consolidation_send_packing"),
    path("packing/", views.packing_legacy, name="packing_root"),
    path("packing/queue/", views.packing_queue, name="packing_queue"),
    path("packing/<int:order_id>/", views.packing_order_detail, name="packing_order_detail"),
    path("packing/<int:order_id>/verify/", views.packing_order_detail, name="item_verification"),
    path("packing/<int:order_id>/box/", views.box_selection, name="box_selection"),
    path("packing/<int:order_id>/process/", views.packing_process, name="packing_process"),
    path("packing/<int:order_id>/label/", views.packing_label, name="packing_label"),
    path("packing/<int:order_id>/success/", views.packing_success, name="packing_success"),
    path("shipping/", views.dispatch_queue, name="shipping_queue"),
    path("shipping/<int:order_id>/", shipping_views.shipment_detail_legacy, name="shipment_detail_legacy"),
    path("shipping/<int:order_id>/carrier/", shipping_views.carrier_selection, name="carrier_selection"),
    path("shipping/<int:order_id>/truck/", shipping_views.truck_assignment_view, name="truck_assignment"),
    path("shipping/<int:order_id>/confirm/", shipping_views.dispatch_confirmation, name="dispatch_confirmation"),
    path("returns/", views.returns_list, name="returns_list"),
    path("returns/request/", views.return_request, name="return_request"),
    path("returns/<int:return_id>/inspect/", views.return_inspection, name="return_inspection"),
    path("users/", views.user_list, name="user_list"),
    path("users/create/", views.create_user, name="create_user"),
    path("settings/roles/", views.role_permissions_page, name="role_permissions"),
    path("settings/system/", views.system_settings, name="system_settings"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout_view, name="logout"),
    path("putaway/", views.putaway, name="putaway"),
    path("warehouse/", views.warehouse_list, name="warehouse_list"),
    path("warehouse/<int:warehouse_id>/", views.warehouse_detail, name="warehouse_detail"),
    path("warehouse/create/", views.create_warehouse, name="create_warehouse"),
    path("warehouse/zones/", views.zone_setup, name="zone_setup"),
    path("warehouse/racks/", views.rack_setup, name="rack_setup"),
    path("warehouse/rack/<int:rack_id>/view/", views.rack_detail_view, name="rack_detail_view"),
    path("warehouse/bins/", views.bin_configuration, name="bin_configuration"),
    path("warehouse/layout/", views.warehouse_layout_map, name="warehouse_layout_map"),
    path("warehouse/create", api_views.warehouse_create_api, name="warehouse_create_api"),
    path("warehouse/list", api_views.warehouse_list_api, name="warehouse_list_api"),
    path("warehouse/<int:warehouse_id>/hierarchy", api_views.warehouse_hierarchy_api, name="warehouse_hierarchy_api"),
    path("zone/create", api_views.zone_create_api, name="zone_create_api"),
    path("zone/<int:zone_id>/update", api_views.zone_update_api, name="zone_update_api"),
    path("zone/<int:zone_id>/delete", api_views.zone_delete_api, name="zone_delete_api"),
    path("zone/list", api_views.zone_list_api, name="zone_list_api"),
    path("aisle/create", api_views.aisle_create_api, name="aisle_create_api"),
    path("aisle/<int:aisle_id>/update", api_views.aisle_update_api, name="aisle_update_api"),
    path("aisle/<int:aisle_id>/delete", api_views.aisle_delete_api, name="aisle_delete_api"),
    path("aisle/list", api_views.aisle_list_api, name="aisle_list_api"),
    path("rack/create", api_views.rack_create_api, name="rack_create_api"),
    path("rack/<int:rack_id>/update", api_views.rack_update_api, name="rack_update_api"),
    path("rack/<int:rack_id>/delete", api_views.rack_delete_api, name="rack_delete_api"),
    path("rack/list", api_views.rack_list_api, name="rack_list_api"),
    path("level/create", api_views.level_create_api, name="level_create_api"),
    path("level/list", api_views.level_list_api, name="level_list_api"),
    path("bin/generate", api_views.bin_generate_api, name="bin_generate_api"),
    path("bin/list", api_views.bin_list_api, name="bin_list_api"),
    path("bin/<int:bin_id>/update", api_views.bin_update_api, name="bin_update_api"),
    path("bin/<int:bin_id>/delete", api_views.bin_delete_api, name="bin_delete_api"),
    path("inventory/skus/", views.sku_list, name="sku_list"),
    path("inventory/skus/create/", views.create_sku, name="create_sku"),
    path("inventory/skus/<int:sku_id>/", views.sku_detail, name="sku_detail"),
    path("sku/create", api_views.sku_create_api, name="sku_create_api"),
    path("sku/list", api_views.sku_list_api, name="sku_list_api"),
    path("inventory/barcode/", views.barcode_generator, name="barcode_generator"),
    path("inventory/packaging/", views.packaging_hierarchy, name="packaging_hierarchy"),
    path("inventory/", views.inventory_list, name="inventory_list"),
    path("inventory/adjustment/", views.stock_adjustment, name="stock_adjustment"),
    path("inventory/list", api_views.inventory_list_api, name="inventory_list_api"),
    path("stock-adjustment", api_views.stock_adjustment_api, name="stock_adjustment_api"),
    path("inventory/transfer/", views.stock_transfer, name="stock_transfer"),
    path("api/inventory/transfer", api_views.stock_transfer_api, name="stock_transfer_api"),
    path("inventory/replenishment/", views.replenishment_tasks, name="replenishment_tasks"),

    # Inbound (Receiving)
    path("inbound/", inbound_views.inbound_po_list, name="inbound_po_list"),
    path("inbound/create/", inbound_views.create_po, name="create_po"),
    path("inbound/<int:po_id>/", inbound_views.dock_arrival, name="inbound_po_detail"),
    path("inbound/<int:po_id>/dock/", inbound_views.dock_arrival, name="dock_arrival"),
    path("inbound/dock-arrival/", inbound_views.inbound_dock_arrival_list, name="inbound_dock_arrival_list"),
    path("inbound/qc/", inbound_views.inbound_qc_list, name="inbound_qc_list"),
    path("inbound/<int:po_id>/receipt/", inbound_views.goods_receipt_view, name="goods_receipt"),
    path("inbound/<int:po_id>/scan/", inbound_views.barcode_scan_view, name="barcode_scan"),
    path("inbound/<int:po_id>/qc/", inbound_views.qc_screen, name="qc_screen"),
    path("inbound/<int:po_id>/staging/", inbound_views.staging_area, name="staging_area"),
    path("inbound/<int:po_id>/staging/create-putaway/", inbound_views.create_putaway_tasks, name="create_putaway_tasks"),
    path("inbound/putaway/tasks/", inbound_views.inbound_putaway_list, name="inbound_putaway_list"),
    path(
        "inbound/putaway/tasks/<int:task_id>/suggested-bin/",
        inbound_views.inbound_putaway_set_suggested_bin,
        name="inbound_putaway_set_suggested_bin",
    ),
    path("inbound/putaway/tasks/<int:task_id>/complete/", inbound_views.inbound_putaway_complete, name="inbound_putaway_complete"),
]
